apiVersion: v1
data:
  mapRoles: |
   - groups:
     - system:masters
     rolearn: arn:aws:iam::310211424080:role/UdacityFlaskDeployCBKubectlRole
     username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::310211424080:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18M0HRW4PJGTW
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-19T00:20:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1505"
  uid: 922449b5-034a-40c3-8c37-62589f7a850f
