apiVersion: v1
data:
  mapRoles: |
   - groups:
     - system:masters
     rolearn: arn:aws:iam::310211424080:role/UdacityFlaskDeployCBKubectlRole
     username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::310211424080:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GMDCAMEUKUZ3
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-19T02:06:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1454"
  uid: b16be595-840f-4576-810f-3a34a63d04cc
